/* типы экшенов */
export const ADD_TODO = 'ADD_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const COMPLETED_TODO = 'COMPLETED_TODO'
export const SET_PRIORITY_TO_TASK = 'SET_PRIORITY_TO_TASK'
export const CLEAR_TODO_LIST = 'CLEAR_TODO_LIST'
export const TODOS_FETCH_DATA_SUCCESS = 'TODOS_FETCH_DATA_SUCCESS'
export const UPDATE_TODO_TEXT = 'UPDATE_TODO_TEXT'

