require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'reduxSaga' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'reduxSagaTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'reduxSaga-tvOS' do
  # Pods for reduxSaga-tvOS

  target 'reduxSaga-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
